// apps/admin-react/app/routes/login/login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { signInWithEmailAndPassword } from 'firebase/auth';
import { Loader2 } from 'lucide-react';

import { Button } from '@front/cn/components/button';
import { Input } from '@front/cn/components/input';
import { Label } from '@front/cn/components/label';
import { auth } from '../../firebase';

const loginSchema = z.object({
  email: z
    .string()
    .min(1, 'Email is required')
    .pipe(z.email({ error: 'Invalid email format' })),
  password: z.string().min(1, 'Password is required'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

function getAuthErrorMessage(code: string): string {
  switch (code) {
    case 'auth/user-not-found':
    case 'auth/invalid-credential':
    case 'auth/wrong-password':
    case 'auth/invalid-email':
      return 'Invalid credentials.';
    case 'auth/user-disabled':
      return 'This account has been disabled.';
    case 'auth/too-many-requests':
      return 'Too many failed login attempts. Please try again later.';
    case 'auth/network-request-failed':
      return 'Network error. Please check your connection.';
    default:
      return 'Authentication failed.';
  }
}

export default function Login() {
  const navigate = useNavigate();
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  async function onSubmit(data: LoginFormValues) {
    setErrorMessage(null);

    try {
      const userCredential = await signInWithEmailAndPassword(
        auth,
        data.email,
        data.password
      );

      if (userCredential.user) {
        navigate('/home');
      }
    } catch (error: unknown) {
      const firebaseError = error as { code?: string };
      const message = firebaseError.code
        ? getAuthErrorMessage(firebaseError.code)
        : 'An unexpected error occurred.';
      setErrorMessage(message);
    }
  }

  return (
    <div className="grid min-h-screen lg:grid-cols-2">
      <div className="hidden lg:flex flex-col justify-between bg-foreground p-10 text-primary-foreground">
        <img
          src="/logos/icon.svg"
          alt="Norseus"
          className="h-20 w-20 brightness-0 invert"
        />
        <div className="space-y-4">
          <blockquote className="text-lg font-medium leading-relaxed">
            &ldquo;Simplify your gym management. Members, plans, schedules
            &mdash; all in one place.&rdquo;
          </blockquote>
          <p className="text-sm text-primary-foreground/60">
            Admin Dashboard
          </p>
        </div>
        <p className="text-xs text-primary-foreground/40">
          &copy; {new Date().getFullYear()} Norseus
        </p>
      </div>

      <div className="flex items-center justify-center p-8">
        <div className="w-full max-w-sm space-y-8">
          <div className="flex justify-center lg:hidden">
            <img src="/logos/logo_name.svg" alt="Norseus" className="h-10" />
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            <div className="grid gap-1.5">
              <Label htmlFor="email-input">Email</Label>
              <Input
                id="email-input"
                type="email"
                placeholder="you@example.com"
                aria-invalid={!!errors.email}
                {...register('email')}
              />
              {errors.email && (
                <p className="text-sm text-destructive">
                  {errors.email.message}
                </p>
              )}
            </div>

            <div className="grid gap-1.5">
              <Label htmlFor="password-input">Password</Label>
              <Input
                id="password-input"
                type="password"
                aria-invalid={!!errors.password}
                {...register('password')}
              />
              {errors.password && (
                <p className="text-sm text-destructive">
                  {errors.password.message}
                </p>
              )}
            </div>

            <Button
              type="submit"
              className="w-full"
              size="lg"
              disabled={isSubmitting}
            >
              {isSubmitting && <Loader2 className="animate-spin" />}
              Sign in
            </Button>

            {errorMessage && (
              <p className="text-center text-sm text-destructive">
                {errorMessage}
              </p>
            )}
          </form>
        </div>
      </div>
    </div>
  );
}

// apps/admin/src/app/pages/login/login.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { signInWithEmailAndPassword, Auth } from '@angular/fire/auth';

import { ButtonComponent } from '@ui';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, ButtonComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginComponent {
  //****************************************************************************
  //* PUBLIC SIGNALS
  //****************************************************************************
  loading = signal(false);
  errorMessage = signal<string | null>(null);

  //****************************************************************************
  //* PRIVATE INJECTIONS
  //****************************************************************************
  private fb = inject(FormBuilder);
  private auth = inject(Auth);
  private router = inject(Router);

  //****************************************************************************
  //* PUBLIC INSTANCE PROPERTIES
  //****************************************************************************
  loginForm: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
  });

  //****************************************************************************
  //* PUBLIC METHODS
  //****************************************************************************
  async onSubmit(): Promise<void> {
    if (this.loginForm.valid) {
      this.loading.set(true);
      this.errorMessage.set(null);
      const { email, password } = this.loginForm.value;

      try {
        const userCredential = await signInWithEmailAndPassword(this.auth, email, password);
        if (userCredential.user) {
          await this.router.navigateByUrl('/home');
        }
      } catch (error: any) {
        let errorMessage = 'An unexpected error occurred.';

        if (error.code) {
          switch (error.code) {
            case 'auth/user-not-found':
            case 'auth/invalid-credential':
            case 'auth/wrong-password':
            case 'auth/invalid-email':
              errorMessage = 'Invalid credentials.';
              break;
            case 'auth/user-disabled':
              errorMessage = 'This account has been disabled.';
              break;
            case 'auth/too-many-requests':
              errorMessage = 'Too many failed login attempts. Please try again later.';
              break;
            case 'auth/network-request-failed':
              errorMessage = 'Network error. Please check your connection.';
              break;
            default:
              errorMessage = error.message || 'Authentication failed.';
          }
        }

        this.errorMessage.set(errorMessage);
      } finally {
        this.loading.set(false);
      }
    } else {
      this.loginForm.markAllAsTouched();
    }
  }
}

<div class="w-full max-w-md p-8 bg-white rounded-xl shadow-lg">
  <form class="form space-y-6 w-full" [formGroup]="loginForm" (ngSubmit)="onSubmit()">
    <h2 class="text-xl text-center mb-4 text-gray-800">Login</h2>

    <div class="grid gap-3">
      <label for="email-input" class="label">Email</label>
      <input
        type="email"
        class="input"
        id="email-input"
        formControlName="email"
        [attr.aria-invalid]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched"
      />
    </div>

    <div class="grid gap-3">
      <label for="password-input" class="label">Password</label>
      <input
        type="password"
        class="input"
        id="password-input"
        formControlName="password"
        [attr.aria-invalid]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched"
      />
    </div>

    <button type="submit" class="btn w-full" [disabled]="loginForm.invalid" ui-button [isLoading]="loading()">
      Login
    </button>

    <ui-select placeholder="Select a fruit" formControlName="fruit"></ui-select>
  </form>

  @if (errorMessage()) {
    <div class="text-red-600 text-center mt-4">
      {{ errorMessage() }}
    </div>
  }
</div>
