// apps/admin-react/app/routes/home/plans/plans-edit.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router';
import { type Resolver, useForm, useFieldArray, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, Loader2, Plus } from 'lucide-react';
import { sileo } from 'sileo';

import { Button } from '@front/cn/components/button';
import { Card, CardContent, CardHeader, CardTitle } from '@front/cn/components/card';
import { Input } from '@front/cn/components/input';
import { Label } from '@front/cn/components/label';
import { Switch } from '@front/cn/components/switch';
import { Textarea } from '@front/cn/components/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@front/cn/components/select';
import { getPlan, updatePlan, getServices } from '@front/services';
import { PlanDuration, PlanDurationNames, ClassLimitType } from '@models/plans';
import type { Plan } from '@models/plans';
import type { Service } from '@models/services';
import { db } from '../../../firebase';
import { useSessionStore } from '../../../stores/session.store';
import { PlanServiceForm } from './components';

interface PlanEditFormValues {
  name: string;
  description: string;
  cost: number;
  duration: {
    type: PlanDuration;
    days: number | null;
  };
  services: {
    serviceId: string;
    classLimitType: ClassLimitType;
    classLimit: number | null;
  }[];
  active: boolean;
}

const planEditSchema = z.object({
  name: z.string().min(1, 'Nombre requerido').max(100, 'Maximo 100 caracteres'),
  description: z.string().max(500, 'Maximo 500 caracteres').default(''),
  cost: z.coerce.number().min(0, 'El costo debe ser mayor o igual a 0'),
  duration: z.object({
    type: z.nativeEnum(PlanDuration),
    days: z.coerce.number().nullable(),
  }),
  services: z.array(z.object({
    serviceId: z.string().min(1, 'Servicio requerido'),
    classLimitType: z.nativeEnum(ClassLimitType),
    classLimit: z.coerce.number().nullable(),
  })).min(1, 'Debe incluir al menos un servicio'),
  active: z.boolean(),
});

export default function PlansEditPage() {
  const { planId } = useParams<{ planId: string }>();
  const navigate = useNavigate();
  const selectedFacility = useSessionStore((s) => s.selectedFacility);
  const [plan, setPlan] = useState<Plan | undefined>();
  const [availableServices, setAvailableServices] = useState<Service[]>([]);
  const [loading, setLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const {
    register,
    handleSubmit,
    control,
    watch,
    reset,
    formState: { errors },
  } = useForm<PlanEditFormValues>({
    resolver: zodResolver(planEditSchema) as Resolver<PlanEditFormValues>,
    defaultValues: {
      name: '',
      description: '',
      cost: 0,
      duration: { type: PlanDuration.MONTHLY, days: null },
      services: [],
      active: true,
    },
  });

  const { fields, append, remove } = useFieldArray({ control, name: 'services' });
  const durationType = watch('duration.type');

  useEffect(() => {
    if (!selectedFacility?.id || !planId) return;

    setLoading(true);
    Promise.all([
      getPlan(db, selectedFacility.id, planId),
      getServices(db, selectedFacility.id),
    ])
      .then(([planResult, servicesResult]) => {
        if (planResult) {
          setPlan(planResult);
          setAvailableServices(servicesResult);
        }
      })
      .finally(() => setLoading(false));
  }, [selectedFacility?.id, planId]);

  useEffect(() => {
    if (!plan) return;
    reset({
      name: plan.name,
      description: plan.description,
      cost: plan.cost,
      duration: plan.duration,
      services: plan.services,
      active: plan.active,
    });
  }, [plan, reset]);

  async function onSubmit(data: PlanEditFormValues) {
    if (!selectedFacility?.id || !planId || !plan) return;

    setIsSaving(true);
    try {
      await updatePlan(db, selectedFacility.id, planId, {
        name: data.name,
        description: data.description ?? '',
        cost: data.cost,
        currency: plan.currency,
        duration: {
          type: data.duration.type,
          days: data.duration.type === PlanDuration.CUSTOM ? data.duration.days : null,
        },
        services: data.services.map((s) => ({
          serviceId: s.serviceId,
          classLimitType: s.classLimitType,
          classLimit: s.classLimitType === ClassLimitType.FIXED ? s.classLimit : null,
        })),
        active: data.active,
      });
      sileo.success({ title: 'Plan actualizado correctamente', duration: 3000 });
      navigate(`/home/plans/${planId}`);
    } catch (error: unknown) {
      const message =
        error && typeof error === 'object' && 'message' in error
          ? (error as { message: string }).message
          : 'Error al actualizar el plan';
      sileo.error({ title: message, duration: 5000 });
    } finally {
      setIsSaving(false);
    }
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!plan) {
    return (
      <div className="mx-auto w-full max-w-3xl space-y-6">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate('/home/plans')}
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <h1 className="text-3xl font-bold tracking-tight">Plan no encontrado</h1>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-3xl mx-auto space-y-6">
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          type="button"
          onClick={() => navigate(`/home/plans/${planId}`)}
        >
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Editar plan</h1>
        </div>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Informacion del plan</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="name">Nombre del plan</Label>
              <Input
                id="name"
                placeholder="Ej. Plan Basico, Plan Premium..."
                aria-invalid={!!errors.name}
                {...register('name')}
              />
              {errors.name && (
                <p className="text-sm text-destructive">{errors.name.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="cost">Costo</Label>
              <Input
                id="cost"
                type="number"
                min={0}
                placeholder="0"
                aria-invalid={!!errors.cost}
                {...register('cost')}
              />
              {errors.cost && (
                <p className="text-sm text-destructive">{errors.cost.message}</p>
              )}
            </div>

            <div className="space-y-2 sm:col-span-2">
              <Label htmlFor="description">
                Descripcion <span className="text-muted-foreground">(opcional)</span>
              </Label>
              <Textarea
                id="description"
                placeholder="Describe brevemente el plan..."
                className="resize-none"
                rows={3}
                aria-invalid={!!errors.description}
                {...register('description')}
              />
              {errors.description && (
                <p className="text-sm text-destructive">{errors.description.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label>Tipo de duracion</Label>
              <Controller
                name="duration.type"
                control={control}
                render={({ field }) => (
                  <Select onValueChange={field.onChange} value={field.value}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.entries(PlanDurationNames).map(([value, label]) => (
                        <SelectItem key={value} value={value}>
                          {label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              />
            </div>

            {durationType === PlanDuration.CUSTOM && (
              <div className="space-y-2">
                <Label htmlFor="days">Dias</Label>
                <Input
                  id="days"
                  type="number"
                  min={1}
                  placeholder="Ej. 45"
                  aria-invalid={!!errors.duration?.days}
                  {...register('duration.days')}
                />
                {errors.duration?.days && (
                  <p className="text-sm text-destructive">{errors.duration.days.message}</p>
                )}
              </div>
            )}

            <div className="flex items-center gap-3 sm:col-span-2">
              <Controller
                name="active"
                control={control}
                render={({ field }) => (
                  <Switch
                    id="active"
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                )}
              />
              <Label htmlFor="active">Plan activo</Label>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Servicios incluidos</CardTitle>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="gap-1"
                onClick={() => append({ serviceId: '', classLimitType: ClassLimitType.UNLIMITED, classLimit: null })}
              >
                <Plus className="h-3.5 w-3.5" />
                Agregar servicio
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-2">
            {fields.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-4">
                No hay servicios agregados. Agrega al menos uno.
              </p>
            )}
            {fields.map((field, index) => (
              <div key={field.id} className="border-b pb-4 last:border-b-0 last:pb-0">
                <PlanServiceForm
                  index={index}
                  control={control}
                  register={register}
                  services={availableServices}
                  onRemove={() => remove(index)}
                  errors={errors}
                />
              </div>
            ))}
            {errors.services?.message && (
              <p className="text-sm text-destructive">{errors.services.message}</p>
            )}
          </CardContent>
        </Card>

        <div className="flex items-center justify-between">
          <Button
            type="button"
            variant="outline"
            onClick={() => navigate(`/home/plans/${planId}`)}
          >
            Cancelar
          </Button>
          <Button type="submit" disabled={isSaving}>
            {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Guardar cambios
          </Button>
        </div>
      </form>
    </div>
  );
}

// apps/admin/src/app/pages/plans/plans-edit/plans-edit.component.ts
import { ChangeDetectionStrategy, Component, effect, inject } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormArray,
  ReactiveFormsModule,
  Validators,
  AbstractControl,
  ValidationErrors,
} from '@angular/forms';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { PlansEditStore } from './plans-edit.store';
import { SessionSignalStore } from '@front/state/session';
import { PlanDuration, PlanDurationNames, ClassLimitType, ClassLimitTypeNames, Plan, PlanService } from '@models/plans';
import { ButtonComponent, SelectModule } from '@ui';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { PlanServiceFormComponent } from '../plans-create/components/plan-service-form';

@Component({
  selector: 'app-plans-edit',
  imports: [ReactiveFormsModule, SelectModule, PlanServiceFormComponent, ButtonComponent, RouterModule, MatSlideToggleModule],
  templateUrl: './plans-edit.component.html',
  styleUrl: './plans-edit.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [PlansEditStore],
})
export class PlansEditComponent {
  private readonly store = inject(PlansEditStore);
  private readonly session = inject(SessionSignalStore);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly fb = inject(FormBuilder);

  readonly plan = this.store.plan;
  readonly services = this.store.services;
  readonly loading = this.store.loading;
  readonly error = this.store.error;
  readonly planDurationNames = PlanDurationNames;
  readonly planDurations = Object.values(PlanDuration);
  readonly classLimitTypeNames = ClassLimitTypeNames;

  form: FormGroup;
  planId: string;

  constructor() {
    this.planId = this.route.snapshot.paramMap.get('id') || '';

    this.form = this.fb.group({
      name: [null, Validators.required],
      description: [''],
      cost: [null, [Validators.required, Validators.min(0)]],
      active: [true, Validators.required],
      duration: this.fb.group({
        type: [PlanDuration.MONTHLY, Validators.required],
        days: [{ value: null, disabled: true }],
      }),
      services: this.fb.array([], this.arrayMinLengthValidator(1)),
    });

    effect(() => {
      const plan = this.plan();
      if (plan) {
        this.form.patchValue({
          name: plan.name,
          description: plan.description,
          cost: plan.cost,
          active: plan.active,
          duration: {
            type: plan.duration.type,
            days: plan.duration.days,
          },
        });

        const servicesArray = this.form.get('services') as FormArray;
        servicesArray.clear();
        plan.services.forEach((service) => {
          servicesArray.push(this.createServiceGroup(service));
        });
      }
    });

    this.form
      .get('duration.type')
      ?.valueChanges.pipe(takeUntilDestroyed())
      .subscribe((type) => {
        const daysControl = this.form.get('duration.days');
        if (type === PlanDuration.CUSTOM) {
          daysControl?.enable();
          daysControl?.setValidators(Validators.required);
        } else {
          daysControl?.disable();
          daysControl?.clearValidators();
        }
        daysControl?.updateValueAndValidity();
      });

    effect(() => {
      const facilityId = this.session.selectedFacility()?.id;
      if (facilityId && this.planId) {
        this.store.loadServices(facilityId);
        this.store.loadPlan({ facilityId, planId: this.planId });
      }
    });
  }

  get servicesArray(): FormArray {
    return this.form.get('services') as FormArray;
  }

  private createServiceGroup(service: PlanService): FormGroup {
    return this.fb.group({
      serviceId: [service.serviceId, Validators.required],
      classLimitType: [service.classLimitType, Validators.required],
      classLimit: [service.classLimit],
    });
  }

  addService() {
    const serviceGroup = this.fb.group({
      serviceId: ['', Validators.required],
      classLimitType: [ClassLimitType.UNLIMITED, Validators.required],
      classLimit: [{ value: null }],
    });

    this.servicesArray.push(serviceGroup);
  }

  removeService(index: number) {
    this.servicesArray.removeAt(index);
  }

  private arrayMinLengthValidator(minLength: number) {
    return (control: AbstractControl): ValidationErrors | null => {
      if (!(control instanceof FormArray)) {
        return null;
      }
      return control.length >= minLength
        ? null
        : {
            minLengthArray: {
              requiredLength: minLength,
              actualLength: control.length,
            },
          };
    };
  }

  async updatePlan() {
    if (this.form.invalid) {
      return;
    }

    const facilityId = this.session.selectedFacility()?.id;
    if (!facilityId) return;

    const formValue = this.form.getRawValue();
    const planServices: PlanService[] = formValue.services.map(
      (service: { serviceId: string; classLimitType: ClassLimitType; classLimit: number | null }) => {
        const planService: PlanService = {
          serviceId: service.serviceId,
          classLimitType: service.classLimitType,
          classLimit: service.classLimit || null,
        };
        return planService;
      },
    );
    const planData: Plan = {
      id: this.planId,
      name: formValue.name,
      description: formValue.description,
      cost: formValue.cost,
      currency: this.plan()?.currency || 'COP',
      duration: {
        type: formValue.duration.type,
        days: formValue.duration.days || null,
      },
      services: planServices,
      active: formValue.active,
    };
    await this.store.updatePlan(planData, facilityId);
    this.router.navigate(['/home/plans', this.planId]);
  }
}

<div class="max-w-4xl mx-auto py-6">
  <div class="flex items-center justify-between mb-8">
    <h1 class="text-3xl font-bold text-slate-900">Editar Plan</h1>
  </div>

  @if (loading()) {
    <div class="flex justify-center items-center py-16">
      <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-primary"></div>
    </div>
  } @else if (plan()) {
    <form [formGroup]="form" (ngSubmit)="updatePlan()" class="space-y-6">
      <div class="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
        <h2 class="text-xl font-semibold text-slate-900 mb-6">Información del Plan</h2>

        <div class="space-y-6">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="space-y-2">
              <label for="name" class="label"> Nombre <span class="text-red-500">*</span> </label>
              <input id="name" class="input" formControlName="name" type="text" placeholder="Ej: Plan Básico" />
            </div>

            <div class="space-y-2">
              <label for="cost" class="label">Costo <span class="text-red-500">*</span></label>
              <input id="cost" class="input" type="number" formControlName="cost" placeholder="0.00" />
            </div>
          </div>

          <div class="space-y-2">
            <label for="description" class="label">Descripción</label>
            <textarea
              id="description"
              class="textarea"
              formControlName="description"
              rows="3"
            ></textarea>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="space-y-2" formGroupName="duration">
              <label for="duration-type" class="label">Duración <span class="text-red-500">*</span></label>
              <ui-select formControlName="type">
                @for (duration of planDurations; track duration) {
                  <ui-option [value]="duration">{{ planDurationNames[duration] }}</ui-option>
                }
              </ui-select>
              @if (form.get('duration.type')?.value === 'custom') {
                <input type="number" class="input mt-2" formControlName="days" placeholder="Número de días" min="1" />
              }
            </div>

            <div class="space-y-2">
              <label class="label" for="plan-status-toggle">Estado</label>
              <div class="flex items-center h-10">
                <mat-slide-toggle id="plan-status-toggle" formControlName="active">
                  {{ form.get('active')?.value ? 'Activo' : 'Inactivo' }}
                </mat-slide-toggle>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-xl font-semibold text-slate-900">Servicios Incluidos</h2>
          <button type="button" class="btn-outline flex items-center gap-2" (click)="addService()">
            <span class="material-symbols-rounded text-lg">add</span>
            Agregar Servicio
          </button>
        </div>

        @if (servicesArray.length === 0) {
          <div class="text-center py-12 text-slate-500 border-2 border-dashed border-slate-200 rounded-lg">
            <span class="material-symbols-rounded text-4xl mb-2 block">fitness_center</span>
            <p class="text-sm">No hay servicios agregados</p>
            <p class="text-xs mt-1">Haz clic en "Agregar Servicio" para comenzar</p>
          </div>
        } @else {
          <div formArrayName="services" class="flex flex-col gap-4">
            @for (serviceGroup of servicesArray.controls; track $index) {
              <app-plan-service-form
                [serviceGroup]="$any(serviceGroup)"
                [services]="services()"
                (remove)="removeService($index)"
              />
            }
          </div>
        }
      </div>

      @if (error()) {
        <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
          <div class="flex items-center gap-2">
            <span class="material-symbols-rounded">error</span>
            <span>{{ error() }}</span>
          </div>
        </div>
      }

      <div class="flex justify-end gap-4">
        <a routerLink="/home/plans/{{ planId }}" class="btn-outline">Cancelar</a>
        <button type="submit" class="btn" ui-button [isLoading]="loading()" [disabled]="form.invalid">
          Guardar Cambios
        </button>
      </div>
    </form>
  }
</div>
