// libs/front/ui-react/src/week-calendar/week-calendar.tsx
import { useMemo } from 'react';
import { DAYS_OF_WEEK, DAY_OF_WEEK_LABELS, type DayOfWeek } from '@models/common';
import {
  type CalendarSlot,
  type SlotPosition,
  getTimeRange,
  calculateSlotPosition,
} from '../schedule.utils';

const SLOT_HEIGHT = 40;

const DAY_SHORT_LABELS: Record<DayOfWeek, string> = {
  mon: 'Lun',
  tue: 'Mar',
  wed: 'Mié',
  thu: 'Jue',
  fri: 'Vie',
  sat: 'Sáb',
  sun: 'Dom',
};

interface WeekCalendarProps {
  slots: CalendarSlot[];
  onSlotClick?: (slotId: string) => void;
}

interface TimeLabel {
  label: string;
  isHourMark: boolean;
}

export function WeekCalendar({ slots, onSlotClick }: WeekCalendarProps) {
  const timeLabels = useMemo<TimeLabel[]>(() => {
    if (slots.length === 0) return [];
    const { minHour, maxHour } = getTimeRange(slots);
    const labels: TimeLabel[] = [];
    for (let hour = minHour; hour <= maxHour; hour++) {
      labels.push({
        label: `${hour.toString().padStart(2, '0')}:00`,
        isHourMark: true,
      });
      if (hour < maxHour) {
        labels.push({
          label: `${hour.toString().padStart(2, '0')}:30`,
          isHourMark: false,
        });
      }
    }
    return labels;
  }, [slots]);

  const calendarHeight = timeLabels.length * SLOT_HEIGHT;

  const slotsByDay = useMemo<Record<DayOfWeek, SlotPosition[]>>(() => {
    const grouped: Record<DayOfWeek, SlotPosition[]> = {
      mon: [],
      tue: [],
      wed: [],
      thu: [],
      fri: [],
      sat: [],
      sun: [],
    };
    if (slots.length === 0) return grouped;
    const { minHour } = getTimeRange(slots);
    for (const slot of slots) {
      grouped[slot.dayOfWeek].push(
        calculateSlotPosition(slot, minHour, SLOT_HEIGHT)
      );
    }
    return grouped;
  }, [slots]);

  if (slots.length === 0) return null;

  return (
    <div className="overflow-x-auto">
      <div className="grid min-w-[600px]" style={{ gridTemplateColumns: '50px repeat(7, 1fr)' }}>
        <div className="border-b border-gray-300" />
        {DAYS_OF_WEEK.map((day) => (
          <div
            key={day}
            className="border-b border-l border-gray-300 bg-gray-50 p-2 text-center text-sm font-semibold"
            title={DAY_OF_WEEK_LABELS[day]}
          >
            {DAY_SHORT_LABELS[day]}
          </div>
        ))}

        <div className="relative" style={{ height: calendarHeight }}>
          {timeLabels.map((slot, i) => (
            <div
              key={slot.label}
              className="absolute right-0 left-0 pr-2 text-right text-xs text-gray-600"
              style={{ top: i * SLOT_HEIGHT, height: SLOT_HEIGHT }}
            >
              <span className="bg-white pr-1">{slot.label}</span>
            </div>
          ))}
        </div>

        {DAYS_OF_WEEK.map((day) => (
          <div
            key={day}
            className="relative border-l border-gray-300"
            style={{ height: calendarHeight }}
          >
            {timeLabels.map((slot, i) => (
              <div
                key={slot.label}
                className={`absolute left-0 right-0 ${
                  i > 0
                    ? slot.isHourMark
                      ? 'border-t border-gray-400'
                      : 'border-t border-gray-200'
                    : ''
                }`}
                style={{ top: i * SLOT_HEIGHT, height: SLOT_HEIGHT }}
              />
            ))}
            {slotsByDay[day].map((position) => (
              <button
                key={position.slot.id}
                type="button"
                onClick={() => onSlotClick?.(position.slot.id)}
                className="absolute left-1 right-1 overflow-hidden rounded bg-blue-500/80 px-2 py-1 text-left text-xs text-white transition-colors hover:bg-blue-600"
                style={{ top: position.top, height: position.height }}
                title="Clic para eliminar"
              >
                {position.slot.displayLabel && (
                  <div className="font-semibold">{position.slot.displayLabel}</div>
                )}
                {position.slot.displaySubLabel && (
                  <div className="text-[10px] opacity-90">{position.slot.displaySubLabel}</div>
                )}
              </button>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

// libs/front/ui/src/calendar/week-calendar/week-calendar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { DAYS_OF_WEEK, DAY_OF_WEEK_LABELS, DayOfWeek } from '@models/common';
import { CalendarSlot, SlotPosition } from './interfaces';
import { calculatePosition, getTimeRange, TimeSlot } from '../utilities';

@Component({
  selector: 'ui-week-calendar',
  standalone: true,
  imports: [],
  templateUrl: './week-calendar.component.html',
  styleUrls: ['./week-calendar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WeekCalendarComponent {
  slots = input.required<CalendarSlot[]>();
  slotClick = output<string>();

  readonly DAYS_OF_WEEK = DAYS_OF_WEEK;
  readonly DAY_OF_WEEK_LABELS = DAY_OF_WEEK_LABELS;
  readonly SLOT_HEIGHT = 40;

  timeSlots = computed<TimeSlot[]>(() => {
    const slots = this.slots();
    if (slots.length === 0) return [];

    const { minHour, maxHour } = getTimeRange(slots);
    const timeSlots: TimeSlot[] = [];

    for (let hour = minHour; hour <= maxHour; hour++) {
      timeSlots.push({
        hour,
        minute: 0,
        label: `${hour.toString().padStart(2, '0')}:00`,
        isHourMark: true,
      });

      if (hour < maxHour) {
        timeSlots.push({
          hour,
          minute: 30,
          label: `${hour.toString().padStart(2, '0')}:30`,
          isHourMark: false,
        });
      }
    }

    return timeSlots;
  });

  calendarHeight = computed<number>(() => {
    const slots = this.timeSlots();
    return slots.length * this.SLOT_HEIGHT;
  });

  slotsByDay = computed<Record<DayOfWeek, SlotPosition[]>>(() => {
    const slots = this.slots();
    const grouped: Record<DayOfWeek, SlotPosition[]> = {
      [DayOfWeek.MONDAY]: [],
      [DayOfWeek.TUESDAY]: [],
      [DayOfWeek.WEDNESDAY]: [],
      [DayOfWeek.THURSDAY]: [],
      [DayOfWeek.FRIDAY]: [],
      [DayOfWeek.SATURDAY]: [],
      [DayOfWeek.SUNDAY]: [],
    };

    if (slots.length === 0) return grouped;

    const { minHour } = getTimeRange(slots);

    slots.forEach((slot) => {
      const position = calculatePosition(slot, minHour, this.SLOT_HEIGHT);
      grouped[slot.dayOfWeek].push(position);
    });

    return grouped;
  });

  getSlotsForDay(day: DayOfWeek): SlotPosition[] {
    return this.slotsByDay()[day] || [];
  }

  getShortDayLabel(day: DayOfWeek): string {
    return DAY_OF_WEEK_LABELS[day].substring(0, 3);
  }

  onSlotClick(slotId: string): void {
    this.slotClick.emit(slotId);
  }
}

<div>
  <div>
    <div class="grid grid-cols-[50px_repeat(7,1fr)] gap-0">
      <div class="border-b border-gray-300"></div>
      @for (day of DAYS_OF_WEEK; track day) {
        <div class="border-b border-l border-gray-300 p-2 text-center font-semibold bg-gray-50">
          {{ getShortDayLabel(day) }}
        </div>
      }

      <div class="relative">
        @for (slot of timeSlots(); track slot.label) {
          <div
            class="absolute left-0 right-0 text-xs text-gray-600 pr-2 text-right"
            [style.top.px]="$index * SLOT_HEIGHT"
            [style.height.px]="SLOT_HEIGHT"
          >
            <span class="bg-white pr-1">{{ slot.label }}</span>
          </div>
        }
      </div>

      @for (day of DAYS_OF_WEEK; track day) {
        <div class="border-l border-gray-300 relative" [style.height.px]="calendarHeight()">
          @for (slot of timeSlots(); track slot.label) {
            <div
              class="absolute left-0 right-0"
              [class.border-t]="$index > 0"
              [class.border-gray-400]="slot.isHourMark && $index > 0"
              [class.border-gray-200]="!slot.isHourMark && $index > 0"
              [style.top.px]="$index * SLOT_HEIGHT"
              [style.height.px]="SLOT_HEIGHT"
            ></div>
          }

          @for (position of getSlotsForDay(day); track position.slot.id) {
            <button
              class="absolute left-1 right-1 bg-blue-500/80 text-white rounded px-2 py-1 text-xs overflow-hidden cursor-pointer hover:bg-blue-600 transition-colors"
              [style.top.px]="position.top"
              [style.height.px]="position.height"
              (click)="onSlotClick(position.slot.id)"
            >
              @if (position.slot.displayLabel) {
                <div class="font-semibold">{{ position.slot.displayLabel }}</div>
              }
              @if (position.slot.displaySubLabel) {
                <div class="text-[10px] opacity-90">{{ position.slot.displaySubLabel }}</div>
              }
            </button>
          }
        </div>
      }
    </div>
  </div>
</div>
