// apps/admin/src/app/pages/plans/plans-detail/plans-detail.component.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { SessionSignalStore } from '@front/state/session';
import { PlansDetailStore } from './plans-detail.store';
import { ClassLimitTypeNames, PlanDurationNames } from '@models/plans';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-plans-detail',
  imports: [RouterModule, CommonModule],
  templateUrl: './plans-detail.component.html',
  styleUrl: './plans-detail.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [PlansDetailStore],
})
export class PlansDetailComponent {
  private readonly store = inject(PlansDetailStore);
  private readonly session = inject(SessionSignalStore);
  private readonly route = inject(ActivatedRoute);

  readonly plan = this.store.plan;
  readonly services = this.store.services;
  readonly loading = this.store.loading;
  readonly error = this.store.error;
  readonly planDurationNames = PlanDurationNames;
  readonly classLimitTypeNames = ClassLimitTypeNames;

  readonly includedServices = computed(() => {
    const plan = this.plan();
    const services = this.services();
    if (!plan || !services) {
      return [];
    }
    return plan.services.map((planService) => {
      const service = services.find((s) => s.id === planService.serviceId);
      return {
        ...planService,
        name: service?.name || 'Servicio no encontrado',
      };
    });
  });

  planId: string;

  constructor() {
    this.planId = this.route.snapshot.paramMap.get('id') || '';
    effect(() => {
      const facilityId = this.session.selectedFacility()?.id;
      if (facilityId && this.planId) {
        this.store.loadPlan({ facilityId, planId: this.planId });
        this.store.loadServices(facilityId);
      }
    })
  }
}

@if (loading()) {
  <div class="flex justify-center items-center py-16">
    <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-primary"></div>
  </div>
} @else if (error()) {
  <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
    <div class="flex items-center gap-2">
      <span class="material-symbols-rounded">error</span>
      <span>{{ error() }}</span>
    </div>
  </div>
} @else if (plan()) {
  <div class="flex items-start justify-between mb-8">
    <div>
      <h1 class="text-3xl font-bold text-slate-900">{{ plan()?.name }}</h1>
      <p class="text-slate-500 mt-1">{{ plan()?.description }}</p>
    </div>
    <div class="flex items-center gap-2">
      <a [routerLink]="['/home/plans/edit', plan()?.id]" class="btn-outline"> Editar </a>
    </div>
  </div>

  <div class="space-y-8">
    <div class="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
      <h2 class="text-xl font-semibold text-slate-900 mb-6">Detalles del Plan</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div class="flex items-center gap-4 p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span class="material-symbols-rounded text-3xl text-primary">payments</span>
          <div>
            <h3 class="font-medium text-slate-500 text-sm">Costo</h3>
            <p class="text-slate-900 text-lg font-semibold">
              {{ plan()?.cost | currency: plan()?.currency : 'symbol' : '1.0-0' }}
            </p>
          </div>
        </div>
        <div class="flex items-center gap-4 p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span class="material-symbols-rounded text-3xl text-primary">timelapse</span>
          <div>
            <h3 class="font-medium text-slate-500 text-sm">Duración</h3>
            <p class="text-slate-900 text-lg font-medium">
              {{
                plan()!.duration.type === 'custom'
                  ? plan()!.duration.days + ' días'
                  : planDurationNames[plan()!.duration.type]
              }}
            </p>
          </div>
        </div>
        <div class="flex items-center gap-4 p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span
            class="material-symbols-rounded text-3xl"
            [class]="plan()!.active ? 'text-green-600' : 'text-slate-500'"
          >
            {{ plan()!.active ? 'toggle_on' : 'toggle_off' }}
          </span>
          <div>
            <h3 class="font-medium text-slate-500 text-sm">Estado</h3>
            <p class="text-lg font-medium" [class]="plan()!.active ? 'text-green-700' : 'text-slate-800'">
              {{ plan()!.active ? 'Activo' : 'Inactivo' }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
      <h2 class="text-xl font-semibold text-slate-900 mb-6">Servicios Incluidos</h2>
      @if (includedServices().length > 0) {
        <ul class="space-y-4">
          @for (service of includedServices(); track service.serviceId) {
            <li class="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-200">
              <span class="font-medium text-slate-800">{{ service.name }}</span>
              <div class="text-right text-sm text-slate-600">
                <p>{{ classLimitTypeNames[service.classLimitType] }}</p>
                @if (service.classLimit) {
                  <p>{{ service.classLimit }} clases</p>
                }
              </div>
            </li>
          }
        </ul>
      } @else {
        <div class="text-center py-12 text-slate-500 border-2 border-dashed border-slate-200 rounded-lg">
          <span class="material-symbols-rounded text-4xl mb-2 block">fitness_center</span>
          <p class="text-sm">Este plan no tiene servicios incluidos.</p>
        </div>
      }
    </div>

    <div class="bg-white rounded-lg shadow-sm border border-slate-200 p-6">
      <h2 class="text-xl font-semibold text-slate-900 mb-6">Usuarios Inscritos</h2>
      <div class="text-center py-12 text-slate-500 border-2 border-dashed border-slate-200 rounded-lg">
        <span class="material-symbols-rounded text-4xl mb-2 block">group</span>
        <p class="text-sm">La tabla de usuarios inscritos se implementará en el futuro.</p>
      </div>
    </div>
  </div>
} @else {
  <div class="text-center text-slate-500 py-16">
    <p>No se encontró el plan.</p>
  </div>
}

// apps/admin-react/app/routes/home/plans/plans-detail.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router';
import { ArrowLeft, Loader2, Pencil, Trash2 } from 'lucide-react';
import { sileo } from 'sileo';

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@front/cn/components/alert-dialog';
import { Badge } from '@front/cn/components/badge';
import { Button } from '@front/cn/components/button';
import { Card, CardContent, CardHeader, CardTitle } from '@front/cn/components/card';
import { Separator } from '@front/cn/components/separator';
import { getPlan, getServices } from '@front/services';
import {
  type Plan,
  PlanDuration,
  PlanDurationNames,
  ClassLimitType,
  ClassLimitTypeNames,
} from '@models/plans';
import type { Service } from '@models/services';
import { db } from '../../../firebase';
import { useSessionStore } from '../../../stores/session.store';
import { deletePlan } from '@front/services';

export default function PlansDetailPage() {
  const { planId } = useParams<{ planId: string }>();
  const navigate = useNavigate();
  const selectedFacility = useSessionStore((s) => s.selectedFacility);

  const [plan, setPlan] = useState<Plan | undefined>();
  const [services, setServices] = useState<Service[]>([]);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    if (!selectedFacility?.id || !planId) return;

    setLoading(true);
    Promise.all([
      getPlan(db, selectedFacility.id, planId),
      getServices(db, selectedFacility.id),
    ])
      .then(([planResult, servicesResult]) => {
        if (!planResult) {
          setNotFound(true);
          return;
        }
        setPlan(planResult);
        setServices(servicesResult);
      })
      .catch(() => setNotFound(true))
      .finally(() => setLoading(false));
  }, [selectedFacility?.id, planId]);

  async function handleDelete() {
    if (!selectedFacility?.id || !planId) return;

    setIsDeleting(true);
    try {
      await deletePlan(db, selectedFacility.id, planId);
      sileo.success({ title: 'Plan eliminado correctamente', duration: 3000 });
      navigate('/home/plans');
    } catch {
      sileo.error({ title: 'Error al eliminar el plan', duration: 3000 });
    } finally {
      setIsDeleting(false);
    }
  }

  function getServiceName(serviceId: string): string {
    return services.find((s) => s.id === serviceId)?.name ?? 'Servicio desconocido';
  }

  function getDurationLabel(): string {
    if (!plan) return '';
    if (plan.duration.type === PlanDuration.CUSTOM) {
      return `${plan.duration.days} dias`;
    }
    return PlanDurationNames[plan.duration.type];
  }

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (notFound || !plan) {
    return (
      <div className="mx-auto w-full max-w-3xl space-y-6">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate('/home/plans')}
          >
            <ArrowLeft className="h-4 w-4" />
            <span className="sr-only">Volver</span>
          </Button>
          <h1 className="text-3xl font-bold tracking-tight">
            Plan no encontrado
          </h1>
        </div>
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground">
            El plan solicitado no existe o fue eliminado.
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="mx-auto w-full max-w-4xl space-y-6">
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => navigate('/home/plans')}
        >
          <ArrowLeft className="h-4 w-4" />
          <span className="sr-only">Volver</span>
        </Button>
        <div className="flex flex-1 items-center gap-3">
          <h1 className="text-3xl font-bold tracking-tight">{plan.name}</h1>
          <Badge variant={plan.active ? 'default' : 'secondary'}>
            {plan.active ? 'Activo' : 'Inactivo'}
          </Badge>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-2" asChild>
            <Link to={`/home/plans/${planId}/edit`}>
              <Pencil className="h-4 w-4" />
              Editar
            </Link>
          </Button>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button
                variant="destructive"
                size="sm"
                className="gap-2"
                disabled={isDeleting}
              >
                {isDeleting ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Trash2 className="h-4 w-4" />
                )}
                Eliminar
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Eliminar plan</AlertDialogTitle>
                <AlertDialogDescription>
                  Esta accion no se puede deshacer. Se eliminara el plan
                  permanentemente.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancelar</AlertDialogCancel>
                <AlertDialogAction variant="destructive" onClick={handleDelete}>
                  Eliminar
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>

      {plan.description && (
        <p className="text-muted-foreground">{plan.description}</p>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Detalles</CardTitle>
        </CardHeader>
        <Separator />
        <CardContent className="pt-6">
          <dl className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Costo</dt>
              <dd className="text-lg font-semibold">
                {plan.cost.toLocaleString()} {plan.currency}
              </dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Duracion</dt>
              <dd className="text-lg font-semibold">{getDurationLabel()}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Estado</dt>
              <dd>
                <Badge variant={plan.active ? 'default' : 'secondary'}>
                  {plan.active ? 'Activo' : 'Inactivo'}
                </Badge>
              </dd>
            </div>
          </dl>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Servicios incluidos</CardTitle>
        </CardHeader>
        <Separator />
        <CardContent className="pt-6">
          {plan.services.length > 0 ? (
            <div className="space-y-3">
              {plan.services.map((ps, index) => (
                <div
                  key={index}
                  className="flex items-center justify-between rounded-lg border p-4"
                >
                  <div>
                    <p className="font-medium">{getServiceName(ps.serviceId)}</p>
                    <p className="text-sm text-muted-foreground">
                      {ClassLimitTypeNames[ps.classLimitType]}
                      {ps.classLimitType === ClassLimitType.FIXED && ps.classLimit
                        ? ` — ${ps.classLimit} clases`
                        : ''}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground text-center py-4">
              Este plan no tiene servicios asociados.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
