// libs/front/ui-react/src/date-week-calendar/date-week-calendar.tsx
import { useMemo } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '@front/cn/utils';
import {
  type DateCalendarSlot,
  type DateSlotPosition,
  getWeekDates,
  formatDateHeader,
  getDateSlotTimeRange,
  calculateDateSlotPosition,
} from '../date-calendar.utils';

const SLOT_HEIGHT = 40;

interface DateWeekCalendarProps {
  slots: DateCalendarSlot[];
  weekStart: Date;
  onWeekChange: (newWeekStart: Date) => void;
  onSlotClick?: (slotId: string) => void;
  minWeekStart?: Date;
  maxWeekStart?: Date;
}

interface TimeLabel {
  label: string;
  isHourMark: boolean;
}

const PREDEFINED_COLORS = ['blue', 'green', 'primary'] as const;

const SLOT_COLOR_CLASSES: Record<(typeof PREDEFINED_COLORS)[number], { base: string; hover: string }> = {
  blue: {
    base: 'bg-blue-500/80 text-white',
    hover: 'hover:bg-blue-600',
  },
  green: {
    base: 'bg-green-500/80 text-white',
    hover: 'hover:bg-green-600',
  },
  primary: {
    base: 'bg-primary text-primary-foreground',
    hover: 'hover:bg-primary/90',
  },
};

function isPredefinedColor(color: string | undefined): color is (typeof PREDEFINED_COLORS)[number] {
  return color != null && PREDEFINED_COLORS.includes(color as (typeof PREDEFINED_COLORS)[number]);
}

const DISABLED_NO_COLOR_CLASSES = 'bg-muted text-muted-foreground opacity-50 cursor-not-allowed';
const DISABLED_WITH_COLOR_CLASSES = 'opacity-60 cursor-not-allowed';
const SELECTED_RING = 'ring-2 ring-primary ring-offset-1';

function isSameWeek(a: Date, b: Date): boolean {
  const aTime = new Date(a);
  aTime.setHours(0, 0, 0, 0);
  const bTime = new Date(b);
  bTime.setHours(0, 0, 0, 0);
  return aTime.getTime() === bTime.getTime();
}

export function DateWeekCalendar({
  slots,
  weekStart,
  onWeekChange,
  onSlotClick,
  minWeekStart,
  maxWeekStart,
}: DateWeekCalendarProps) {
  const weekDates = useMemo(() => getWeekDates(weekStart), [weekStart]);

  const canGoPrev = !minWeekStart || !isSameWeek(weekStart, minWeekStart);
  const canGoNext = !maxWeekStart || !isSameWeek(weekStart, maxWeekStart);

  function handlePrev() {
    if (!canGoPrev) return;
    const prev = new Date(weekStart);
    prev.setDate(prev.getDate() - 7);
    onWeekChange(prev);
  }

  function handleNext() {
    if (!canGoNext) return;
    const next = new Date(weekStart);
    next.setDate(next.getDate() + 7);
    onWeekChange(next);
  }

  const timeLabels = useMemo<TimeLabel[]>(() => {
    if (slots.length === 0) return [];
    const { minHour, maxHour } = getDateSlotTimeRange(slots);
    const labels: TimeLabel[] = [];
    for (let hour = minHour; hour <= maxHour; hour++) {
      labels.push({
        label: `${hour.toString().padStart(2, '0')}:00`,
        isHourMark: true,
      });
      if (hour < maxHour) {
        labels.push({
          label: `${hour.toString().padStart(2, '0')}:30`,
          isHourMark: false,
        });
      }
    }
    return labels;
  }, [slots]);

  const calendarHeight = timeLabels.length * SLOT_HEIGHT;

  const slotsByDateIndex = useMemo(() => {
    const grouped: DateSlotPosition[][] = Array.from({ length: 7 }, () => []);
    if (slots.length === 0) return grouped;

    const { minHour } = getDateSlotTimeRange(slots);
    const weekStartTime = weekStart.getTime();

    for (const slot of slots) {
      const slotDate = new Date(slot.date);
      slotDate.setHours(0, 0, 0, 0);
      const diffDays = Math.round((slotDate.getTime() - weekStartTime) / (1000 * 60 * 60 * 24));
      if (diffDays >= 0 && diffDays < 7) {
        grouped[diffDays].push(calculateDateSlotPosition(slot, minHour, SLOT_HEIGHT));
      }
    }

    return grouped;
  }, [slots, weekStart]);

  if (slots.length === 0) return null;

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <button
          type="button"
          onClick={handlePrev}
          disabled={!canGoPrev}
          className={cn(
            'inline-flex h-8 w-8 items-center justify-center rounded-md transition-colors',
            canGoPrev
              ? 'hover:bg-accent text-foreground'
              : 'text-muted-foreground cursor-not-allowed opacity-50'
          )}
        >
          <ChevronLeft className="h-4 w-4" />
        </button>
        <span className="text-sm font-medium">
          {formatDateHeader(weekDates[0])} – {formatDateHeader(weekDates[6])}
        </span>
        <button
          type="button"
          onClick={handleNext}
          disabled={!canGoNext}
          className={cn(
            'inline-flex h-8 w-8 items-center justify-center rounded-md transition-colors',
            canGoNext
              ? 'hover:bg-accent text-foreground'
              : 'text-muted-foreground cursor-not-allowed opacity-50'
          )}
        >
          <ChevronRight className="h-4 w-4" />
        </button>
      </div>

      <div className="overflow-x-auto">
        <div
          className="grid min-w-[600px]"
          style={{ gridTemplateColumns: '50px repeat(7, 1fr)' }}
        >
          <div className="border-b border-border" />
          {weekDates.map((date, i) => (
            <div
              key={i}
              className="border-b border-l border-border bg-muted/50 p-2 text-center text-sm font-semibold"
            >
              {formatDateHeader(date)}
            </div>
          ))}

          <div className="relative" style={{ height: calendarHeight }}>
            {timeLabels.map((tl, i) => (
              <div
                key={tl.label}
                className="absolute right-0 left-0 pr-2 text-right text-xs text-muted-foreground"
                style={{ top: i * SLOT_HEIGHT, height: SLOT_HEIGHT }}
              >
                <span className="bg-background pr-1">{tl.label}</span>
              </div>
            ))}
          </div>

          {weekDates.map((_, dayIdx) => (
            <div
              key={dayIdx}
              className="relative border-l border-border"
              style={{ height: calendarHeight }}
            >
              {timeLabels.map((tl, i) => (
                <div
                  key={tl.label}
                  className={cn(
                    'absolute left-0 right-0',
                    i > 0 && (tl.isHourMark ? 'border-t border-border' : 'border-t border-border/50')
                  )}
                  style={{ top: i * SLOT_HEIGHT, height: SLOT_HEIGHT }}
                />
              ))}
              {slotsByDateIndex[dayIdx].map((position) => {
                const { slot } = position;
                const isDisabled = slot.isDisabled === true;
                const isSelected = slot.isSelected === true;
                const isCustomColor = slot.color != null && !isPredefinedColor(slot.color);

                const colorKey = slot.color ?? 'blue';
                const colorClasses = isPredefinedColor(colorKey)
                  ? SLOT_COLOR_CLASSES[colorKey]
                  : SLOT_COLOR_CLASSES.blue;

                const disabledClasses = slot.color
                  ? isCustomColor
                    ? DISABLED_WITH_COLOR_CLASSES
                    : cn(colorClasses.base, DISABLED_WITH_COLOR_CLASSES)
                  : DISABLED_NO_COLOR_CLASSES;

                const baseClasses = isCustomColor
                  ? cn('text-white', !isDisabled && 'hover:opacity-90')
                  : cn(colorClasses.base, !isDisabled && colorClasses.hover);

                const inlineStyle: React.CSSProperties = {
                  top: position.top,
                  height: position.height,
                  ...(isCustomColor && slot.color ? { backgroundColor: slot.color } : {}),
                };

                return (
                  <button
                    key={slot.id}
                    type="button"
                    disabled={isDisabled}
                    onClick={() => {
                      if (!isDisabled) onSlotClick?.(slot.id);
                    }}
                    className={cn(
                      'absolute left-1 right-1 overflow-hidden rounded px-2 py-1 text-left text-xs transition-colors',
                      isDisabled ? disabledClasses : baseClasses,
                      isSelected && !isDisabled && SELECTED_RING
                    )}
                    style={inlineStyle}
                  >
                    {slot.displayLabel && (
                      <div className="font-semibold">{slot.displayLabel}</div>
                    )}
                    {slot.displaySubLabel && (
                      <div className="text-[10px] opacity-90">{slot.displaySubLabel}</div>
                    )}
                  </button>
                );
              })}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// libs/front/ui/src/calendar/date-week-calendar/date-week-calendar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { DateCalendarSlot, DateSlotPosition } from './interfaces';
import { TimeSlot } from '../utilities';
import { calculateDateSlotPosition, getDateTimeRange } from './utilities';
import {
  formatDayLabel,
  formatMonthYear,
  getDateKey,
  getWeekDates,
  getWeekEnd,
  isSameWeek,
  isToday,
  isDateInRange,
} from '../utilities/date-utilities';
import { getWeekStart } from '@front/utils';

@Component({
  selector: 'ui-date-week-calendar',
  templateUrl: './date-week-calendar.component.html',
  styleUrls: ['./date-week-calendar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DateWeekCalendarComponent<T> {
  slots = input.required<DateCalendarSlot<T>[]>();
  currentWeekDate = input<Date>(new Date());
  minDate = input<Date | undefined>();
  maxDate = input<Date | undefined>();

  slotClick = output<{ slotId: string; isSelected: boolean }>();
  weekChange = output<{ start: Date; end: Date }>();

  readonly SLOT_HEIGHT = 40;

  private currentDisplayWeek = signal<Date>(new Date());

  weekDates = computed<Date[]>(() => {
    const refDate = this.currentDisplayWeek();
    return getWeekDates(refDate);
  });

  monthYear = computed<string>(() => {
    const currentWeek = this.currentDisplayWeek();
    return formatMonthYear(currentWeek);
  });

  canGoPrevious = computed<boolean>(() => {
    const minDate = this.minDate();
    if (!minDate) return true;

    const currentWeekStart = getWeekStart(this.currentDisplayWeek());
    const previousWeekStart = new Date(currentWeekStart);
    previousWeekStart.setDate(previousWeekStart.getDate() - 7);

    const previousWeekEnd = new Date(previousWeekStart);
    previousWeekEnd.setDate(previousWeekEnd.getDate() + 6);
    previousWeekEnd.setHours(23, 59, 59, 999);

    const minDateStart = new Date(minDate);
    minDateStart.setHours(0, 0, 0, 0);

    return minDateStart <= previousWeekStart || (minDateStart >= previousWeekStart && minDateStart <= previousWeekEnd);
  });

  canGoNext = computed<boolean>(() => {
    const maxDate = this.maxDate();
    if (!maxDate) return true;

    const currentWeekStart = getWeekStart(this.currentDisplayWeek());
    const nextWeekStart = new Date(currentWeekStart);
    nextWeekStart.setDate(nextWeekStart.getDate() + 7);

    const maxDateOnly = new Date(maxDate);
    maxDateOnly.setHours(0, 0, 0, 0);

    return nextWeekStart <= maxDateOnly;
  });

  isCurrentWeek = computed<boolean>(() => {
    const today = new Date();
    return isSameWeek(this.currentDisplayWeek(), today);
  });

  timeSlots = computed<TimeSlot[]>(() => {
    const slots = this.slots();
    if (slots.length === 0) return [];

    const { minHour, maxHour } = getDateTimeRange(slots);
    const timeSlots: TimeSlot[] = [];

    for (let hour = minHour; hour <= maxHour; hour++) {
      timeSlots.push({
        hour,
        minute: 0,
        label: `${hour.toString().padStart(2, '0')}:00`,
        isHourMark: true,
      });

      if (hour < maxHour) {
        timeSlots.push({
          hour,
          minute: 30,
          label: `${hour.toString().padStart(2, '0')}:30`,
          isHourMark: false,
        });
      }
    }

    return timeSlots;
  });

  calendarHeight = computed<number>(() => {
    const slots = this.timeSlots();
    return slots.length * this.SLOT_HEIGHT;
  });

  slotsByDate = computed<Record<string, DateSlotPosition<T>[]>>(() => {
    const slots = this.slots();
    const grouped: Record<string, DateSlotPosition<T>[]> = {};

    if (slots.length === 0) return grouped;

    const { minHour } = getDateTimeRange(slots);
    const minDate = this.minDate();
    const maxDate = this.maxDate();

    slots.forEach((slot) => {
      const dateKey = getDateKey(slot.date);
      if (!grouped[dateKey]) {
        grouped[dateKey] = [];
      }

      const isDisabled = slot.disabled || !isDateInRange(slot.date, minDate, maxDate);
      const position = calculateDateSlotPosition(slot, minHour, this.SLOT_HEIGHT, isDisabled);
      grouped[dateKey].push(position);
    });

    return grouped;
  });

  constructor() {
    const initialDate = this.currentWeekDate();
    this.currentDisplayWeek.set(initialDate);
  }

  getSlotsForDate(date: Date): DateSlotPosition<T>[] {
    const dateKey = getDateKey(date);
    return this.slotsByDate()[dateKey] || [];
  }

  isSlotDisabled(slot: DateCalendarSlot<T>): boolean {
    return slot.disabled || !isDateInRange(slot.date, this.minDate(), this.maxDate());
  }

  getDayLabel(date: Date): { day: string; number: number } {
    return formatDayLabel(date);
  }

  isDateToday(date: Date): boolean {
    return isToday(date);
  }

  goToToday(): void {
    const today = new Date();
    this.currentDisplayWeek.set(today);
    this.emitWeekChange();
  }

  goToPreviousWeek(): void {
    if (!this.canGoPrevious()) return;

    const current = this.currentDisplayWeek();
    const previous = new Date(current);
    previous.setDate(previous.getDate() - 7);
    this.currentDisplayWeek.set(previous);
    this.emitWeekChange();
  }

  goToNextWeek(): void {
    if (!this.canGoNext()) return;

    const current = this.currentDisplayWeek();
    const next = new Date(current);
    next.setDate(next.getDate() + 7);
    this.currentDisplayWeek.set(next);
    this.emitWeekChange();
  }

  onSlotClick(slot: DateCalendarSlot<T>): void {
    if (this.isSlotDisabled(slot)) return;
    this.slotClick.emit({ slotId: slot.id, isSelected: !slot.isSelected });
  }

  onDayHeaderClick(date: Date): void {
    const slotsForDate = this.getSlotsForDate(date);
    const enabledSlots = slotsForDate.filter((slot) => !slot.isDisabled);

    if (enabledSlots.length === 0) return;

    const allSelected = enabledSlots.every((slot) => slot.slot.isSelected);
    const newState = !allSelected;

    enabledSlots.forEach((slot) => {
      this.slotClick.emit({ slotId: slot.slot.id, isSelected: newState });
    });
  }

  getSlotClasses(): string {
    return 'cursor-pointer';
  }

  getSlotColorClasses(position: DateSlotPosition<T>): string {
    if (position.isDisabled) {
      return 'bg-gray-300 text-gray-500 cursor-not-allowed opacity-60';
    }

    if (position.slot.isSelected) {
      return 'bg-blue-700/80 hover:bg-blue-800/90 text-white';
    }

    return 'bg-blue-500/60 hover:bg-blue-600/80 text-white';
  }

  private emitWeekChange(): void {
    const start = getWeekStart(this.currentDisplayWeek());
    const end = getWeekEnd(this.currentDisplayWeek());
    this.weekChange.emit({ start, end });
  }
}

<div>
  <div class="flex items-center justify-between mb-4 py-2">
    <div class="text-xl font-semibold text-neutral-600">
      <span>{{ monthYear() }}</span>
    </div>

    <div class="flex items-center gap-2">
      <button
        class="btn-icon-outline"
        [disabled]="!canGoPrevious()"
        (click)="goToPreviousWeek()"
      >
        <span class="material-symbols-rounded">chevron_left</span>
      </button>

      <button
        class="btn-secondary px-4 py-2"
        [disabled]="isCurrentWeek()"
        (click)="goToToday()"
      >
        Hoy
      </button>

      <button
        class="btn-icon-outline"
        [disabled]="!canGoNext()"
        (click)="goToNextWeek()"
      >
        <span class="material-symbols-rounded">chevron_right</span>
      </button>
    </div>
  </div>

  <div class="overflow-x-auto">
    <div class="grid grid-cols-[50px_repeat(7,1fr)] gap-0">
      <div class="border-b border-gray-300"></div>

      @for (date of weekDates(); track date.toISOString()) {
        <button
          class="border-b border-l border-gray-300 p-2 text-center bg-gray-50 cursor-pointer hover:bg-gray-100 transition-colors"
          [class.bg-blue-50]="isDateToday(date)"
          (click)="onDayHeaderClick(date)"
        >
          <div class="font-semibold text-sm">{{ getDayLabel(date).day }}</div>
          <div
            class="text-lg font-bold"
            [class.text-blue-600]="isDateToday(date)"
          >
            {{ getDayLabel(date).number }}
          </div>
        </button>
      }

      <div class="relative">
        @for (slot of timeSlots(); track slot.label) {
          <div
            class="absolute left-0 right-0 text-xs text-gray-600 pr-2 text-right"
            [style.top.px]="$index * SLOT_HEIGHT"
            [style.height.px]="SLOT_HEIGHT"
          >
            <span class="bg-white pr-1">{{ slot.label }}</span>
          </div>
        }
      </div>

      @for (date of weekDates(); track date.toISOString()) {
        <div class="border-l border-gray-300 relative" [style.height.px]="calendarHeight()">
          @for (slot of timeSlots(); track slot.label) {
            <div
              class="absolute left-0 right-0"
              [class.border-t]="$index > 0"
              [class.border-gray-400]="slot.isHourMark && $index > 0"
              [class.border-gray-200]="!slot.isHourMark && $index > 0"
              [style.top.px]="$index * SLOT_HEIGHT"
              [style.height.px]="SLOT_HEIGHT"
            ></div>
          }

          @for (position of getSlotsForDate(date); track position.slot.id) {
            <button
              class="absolute left-1 right-1 rounded px-2 py-1 text-xs overflow-hidden transition-all duration-200"
              [class]="getSlotColorClasses(position)"
              [disabled]="position.isDisabled"
              [style.top.px]="position.top"
              [style.height.px]="position.height"
              (click)="onSlotClick(position.slot)">
              @if (position.slot.displayLabel) {
                <div class="font-semibold">{{ position.slot.displayLabel }}</div>
              }
              @if (position.slot.displaySubLabel) {
                <div class="text-[10px] opacity-90" [innerHTML]="position.slot.displaySubLabel"></div>
              }
            </button>
          }
        </div>
      }
    </div>
  </div>
</div>
